### ISSUE TITLE
pygtk should be compatible with 3.8

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#114]
Todo...

**Comment by dputhier** [comment]
Presently the issue main is related to multiprocessing. Below the message I get upon installation:

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
          exitcode = _main(fd, parent_sentinel)
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
          prepare(preparation_data)
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
          _fixup_main_from_path(data['init_main_from_path'])
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
          main_content = runpy.run_path(main_path,
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/runpy.py", line 265, in run_path
          return _run_module_code(code, init_globals, run_name,
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/runpy.py", line 97, in _run_module_code
          _run_code(code, mod_globals, init_globals,
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/runpy.py", line 87, in _run_code
          exec(code, run_globals)
        File "/private/tmp/test.py", line 2, in <module>
          MANAGER_LIST = multiprocessing.Manager().list()
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/context.py", line 57, in Manager
          m.start()
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/managers.py", line 579, in start
          self._process.start()
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/process.py", line 121, in start
          self._popen = self._Popen(self)
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
          return Popen(process_obj)
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
          super().__init__(process_obj)
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
          self._launch(process_obj)
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
          prep_data = spawn.get_preparation_data(process_obj._name)
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
          _check_not_importing_main()
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
          raise RuntimeError('''
      RuntimeError:
              An attempt has been made to start a new process before the
              current process has finished its bootstrapping phase.

              This probably means that you are not using fork to start your
              child processes and you have forgotten to use the proper idiom
              in the main module:

                  if __name__ == '__main__':
                      freeze_support()
                      ...

              The "freeze_support()" line can be omitted if the program
              is not going to be frozen to produce an executable.
      Traceback (most recent call last):
        File "test.py", line 2, in <module>
          MANAGER_LIST = multiprocessing.Manager().list()
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/context.py", line 57, in Manager
          m.start()
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/managers.py", line 583, in start
          self._address = reader.recv()
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/connection.py", line 250, in recv
          buf = self._recv_bytes()
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
          buf = self._recv(4)
        File "/Users/puthier/miniconda3/envs/python_dev_38.2/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
          raise EOFError
      EOFError

**Comment by dputhier** [comment]
Fixed in 1.2.3
