### ISSUE TITLE
gtftk coverage with -x / --matrix-out fails

### ISSUE THREAD

**Issue by guillaumecharbonnier** [dputhier/pygtftk#116]
Using v1.1.0 installed from bioconda, I get the error below when using gtftk coverage with -x / --matrix-out argument. It works without this argument.

```
$ gtftk coverage -x --inputfile ../mw-aliomari2020/inp/bed/ikE120_peak_mm10.bed --outputfile out/gtftk/coverage_-x_chrominfo-mm10_bed-mm10-ikE120-peak_bw-mm10-immgen-atac.txt --chrom-info out/gunzip/to-stdout/rsync/ucsc/goldenPath/mm10/database/chromInfo.txt out/ln/alias/immgen_atac/GN.BM.bw out/ln/alias/immgen_atac/GN.Sp.bw 
Traceback (most recent call last):
  File "/gpfs/projects/spicuglia/mw-aliomari2020/.snakemake/conda/da389f9b/bin/gtftk", line 104, in <module>
    args = main()
  File "/gpfs/projects/spicuglia/mw-aliomari2020/.snakemake/conda/da389f9b/bin/gtftk", line 89, in main
    CmdManager.run(args)
  File "/gpfs/projects/spicuglia/mw-aliomari2020/.snakemake/conda/da389f9b/lib/python3.7/site-packages/pygtftk/cmd_manager.py", line 958, in run
    fun(**args)
  File "/gpfs/projects/spicuglia/mw-aliomari2020/.snakemake/conda/da389f9b/lib/python3.7/site-packages/pygtftk/plugins/coverage.py", line 349, in coverage
    df_first = df_first.ix[:, [0, 1, 2, 3, 5, 4]]
  File "/gpfs/projects/spicuglia/mw-aliomari2020/.snakemake/conda/da389f9b/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'
```

**Comment by dputhier** [comment]
Hi Guillaume:
What is the output of the command below ?

      gtftk -s 

Best

**Comment by guillaumecharbonnier** [comment]
```
$ gtftk -s

- pygtftk version : 1.1.0
- pygtftk path : /gpfs/projects/spicuglia/mw-aliomari2020/.snakemake/conda/da389f9b/lib/python3.7/site-packages/pygtftk
- python version : sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
- python path : /gpfs/projects/spicuglia/mw-aliomari2020/.snakemake/conda/da389f9b
- pandas version : 1.0.3
- Bedtools version : bedtools v2.29.2
- pybedtools version : 0.8.1
- pyBigWig version : 0.3.13
- uname : posix.uname_result(sysname='Linux', nodename='sacapus', release='2.6.32-504.12.2.el6.x86_64', version='#1 SMP Wed Mar 11 22:03:14 UTC 2015', machine='x86_64')
```

**Comment by dputhier** [comment]
What I thought... A classical process of deprecation in pandas...
https://stackoverflow.com/questions/59991397/attributeerror-dataframe-object-has-no-attribute-ix
Will have to have a look...

**Comment by dputhier** [comment]
I was also thinking about the score computed by gtftk coverage. By default, this is the mean coverage in the region. It can also be the sum (i.e integral of the signal in the region). If you divide the sum by the mean size of your fragment it should give you something rather close to what would be computed based on fragments coordinates enclosed in a BAM (but If you have BAMs, I would favor featureCounts here).
Best
