### ISSUE TITLE
splicing_site issue with input key

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#124]
╰─ gtftk add_exon_nb -i pygtftk/data/mini_real/mini_real.gtf.gz -V 1 | gtftk splicing_site -V 1 -o splice_sites.bed
   |-- 11:49-INFO-splicing_site : Instantiating a GTF.
   |-- 11:49-INFO-add_exon_nb : Instantiating a GTF.
   |-- 11:49-INFO-add_exon_nb : Instantiating a GTF.
   |-- 11:49-INFO-add_exon_nb : Writing a GTF.
   |-- 11:49-INFO-add_exon_nb : GTF written.
  Traceback (most recent call last):
    File "/Users/puthier/anaconda3/envs/python_dev_37/bin/gtftk", line 4, in <module>
      __import__('pkg_resources').run_script('pygtftk==1.1.4', 'gtftk')
    File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
      self.require(requires)[0].run_script(script_name, ns)
    File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
      exec(code, namespace, namespace)
    File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.1.4-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/gtftk", line 104, in <module>
      args = main()
    File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.1.4-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/gtftk", line 89, in main
      CmdManager.run(args)
    File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.1.4-py3.7-macosx-10.9-x86_64.egg/pygtftk/cmd_manager.py", line 958, in run
      fun(**args)
    File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.1.4-py3.7-macosx-10.9-x86_64.egg/pygtftk/plugins/splicing_site.py", line 94, in splicing_site
      if int(i[5]) < nb_exons[i[4]]:
  ValueError: invalid literal for int() with base 10: '?'

**Comment by dputhier** [comment]
Fixed.
