### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be incompatible with each other:

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#145]
Got this message ("UnsatisfiableError: The following specifications were found to be incompatible with each other") but without any listed dependency....

          $ conda create -n ologram python=3.7
          $ conda activate ologram
          $ conda install -c bioconda pygtftk
          Collecting package metadata (current_repodata.json): done
          Solving environment: failed with initial frozen solve. Retrying with flexible solve.
          Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
          Collecting package metadata (repodata.json): done
          Solving environment: failed with initial frozen solve. Retrying with flexible solve.
          Solving environment: - 
          Found conflicts! Looking for incompatible packages.
          This can take several minutes.  Press CTRL-C to abort.
          failed                                                                                                        
          
          UnsatisfiableError: The following specifications were found to be incompatible with each other:
          
          Output in format: Requested package -> Available versions

I tried to remove any Python lib installed in my home directory but without success (rm -rf .local/lib/python*).

      $ uname -a

      Linux V-PP-30-LUM-003 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

@guillaumecharbonnier do you have any idea ?

**Comment by guillaumecharbonnier** [comment]
Hi @dputhier, I have just tried to install it with no issue as described below. The installed python is 3.7. Installing software after the creation of the conda environment often lead to failures.

```
$ conda env create -f pygtftk.yaml
$ cat pygtftk.yaml 
name:
  pygtftk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pygtftk
```

**Comment by dputhier** [comment]
@guillaumecharbonnier Hi Guillaume,
I also managed to install it on a Linux and OSX machine. But for unknown reason I was unable to install it on this specific machine (which correspond to student machines @ AMU...). I was unable to get additional information regarding the issue...

**Comment by guillaumecharbonnier** [comment]
Any insight with increased verbosity?
```
  -v, --verbose         Use once for info, twice for debug, three times for
                        trace.
```

**Comment by dputhier** [comment]
Thank you Guillaume... But nothing really meaningful...

    $ python --version
    Python 3.7.9
    (ologram_py37) V-PP-30-LUM-003 puthier ~
    $ conda config --set unsatisfiable_hints True
    (ologram_py37) V-PP-30-LUM-003 puthier ~
    $ conda install -v -c bioconda pygtftk  
    Collecting package metadata (current_repodata.json): ...working... done
    Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): ...working... done
    Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: ...working... 
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.
    failed                                                                                                                                             
    Traceback (most recent call last):
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 815, in _run_sat
        ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/resolve.py", line 1320, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError: 
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.

    conda config --set unsatisfiable_hints True
                

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 308, in install
        raise e
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 295, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 704, in _add_specs
        ssc.r.find_conflicts(spec_set)
      File "/amuhome/puthier/miniconda3/lib/python3.8/site-packages/conda/resolve.py", line 352, in find_conflicts
        raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
    conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

    Output in format: Requested package -> Available versions
