### ISSUE TITLE
TypeError: a bytes-like object is required, not 'tuple'

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#152]
Hi @qferre ,
I think your last commits introduced an issue (maybe "Revised multiprocessing") . This command worked with commit  dd6d23fa6d134822291d94b5271313258bc9c36d .

        gtftk ologram -z -f -w -q -c mm10 -p selected_tf/SRX2901288-Fos-Blood.bed  --more-bed `ls selected_tf/* | grep -vi fos`   --more-bed-multiple-overlap -k 16 -V 3  -j summed_bp_overlaps_pvalue -a summed_bp_overlaps_pvalue -g 0.05 -D -o SRX2901288-Fos

		concurrent.futures.process._RemoteTraceback:
		"""
		Traceback (most recent call last):
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
		    r = call_item.fn(*call_item.args, **call_item.kwargs)
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.2.8-py3.7-macosx-10.9-x86_64.egg/pygtftk/stats/intersect/overlap_stats_compute.py", line 413, in index_all_these
		    oc.NPARRAY_which_combis_match_with(all_combis, combi, exact) for combi in combis_to_index
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.2.8-py3.7-macosx-10.9-x86_64.egg/pygtftk/stats/intersect/overlap_stats_compute.py", line 413, in <listcomp>
		    oc.NPARRAY_which_combis_match_with(all_combis, combi, exact) for combi in combis_to_index
		  File "pygtftk/stats/intersect/overlap/overlap_regions.pyx", line 510, in pygtftk.stats.intersect.overlap.overlap_regions.__pyx_fuse_0NPARRAY_which_combis_match_with
		  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
		  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
		TypeError: a bytes-like object is required, not 'tuple'
		"""

		The above exception was the direct cause of the following exception:

		Traceback (most recent call last):
		  File "/Users/puthier/anaconda3/envs/python_dev_37/bin/gtftk", line 4, in <module>
		    __import__('pkg_resources').run_script('pygtftk==1.2.8', 'gtftk')
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
		    self.require(requires)[0].run_script(script_name, ns)
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
		    exec(code, namespace, namespace)
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.2.8-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/gtftk", line 110, in <module>
		    args = main()
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.2.8-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/gtftk", line 94, in main
		    CmdManager.run(args)
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.2.8-py3.7-macosx-10.9-x86_64.egg/pygtftk/cmd_manager.py", line 955, in run
		    fun(**args)
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.2.8-py3.7-macosx-10.9-x86_64.egg/pygtftk/plugins/ologram.py", line 950, in ologram
		    multiple_overlap_custom_combis=multiple_overlap_custom_combis)
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.2.8-py3.7-macosx-10.9-x86_64.egg/pygtftk/stats/intersect/overlap_stats_shuffling.py", line 491, in compute_overlap_stats
		    multiple_overlap_custom_combis=multiple_overlap_custom_combis)
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/site-packages/pygtftk-1.2.8-py3.7-macosx-10.9-x86_64.egg/pygtftk/stats/intersect/overlap_stats_compute.py", line 978, in stats_multiple_overlap
		    mappings.append(future.result())
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/concurrent/futures/_base.py", line 428, in result
		    return self.__get_result()
		  File "/Users/puthier/anaconda3/envs/python_dev_37/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
		    raise self._exception
		TypeError: a bytes-like object is required, not 'tuple'

**Comment by qferre** [comment]
Fixed in the current develop branch. This was due to a commit I pushed by mistake.
