### ISSUE TITLE
ImportError: libhts.so.2

### ISSUE THREAD

**Issue by yaskermezli** [dputhier/pygtftk#153]
Hi, 

I'm getting this error  after installation of gtftk on cluster : 

> Traceback (most recent call last):
  File "/home/kermezly/anaconda3/envs/pygtftk/bin/gtftk", line 27, in <module>
    from pygtftk.cmd_manager import CmdManager
  File "/home/kermezly/anaconda3/envs/pygtftk/lib/python3.6/site-packages/pygtftk/cmd_manager.py", line 27, in <module>
    from pygtftk.arg_formatter import ArgFormatter
  File "/home/kermezly/anaconda3/envs/pygtftk/lib/python3.6/site-packages/pygtftk/arg_formatter.py", line 14, in <module>
    import pybedtools
  File "/home/kermezly/anaconda3/envs/pygtftk/lib/python3.6/site-packages/pybedtools/__init__.py", line 12, in <module>
    from . import contrib
  File "/home/kermezly/anaconda3/envs/pygtftk/lib/python3.6/site-packages/pybedtools/contrib/__init__.py", line 3, in <module>
    from . import venn_maker
  File "/home/kermezly/anaconda3/envs/pygtftk/lib/python3.6/site-packages/pybedtools/contrib/venn_maker.py", line 12, in <module>
    from pybedtools import helpers
  File "/home/kermezly/anaconda3/envs/pygtftk/lib/python3.6/site-packages/pybedtools/helpers.py", line 13, in <module>
    import pysam
  File "/home/kermezly/anaconda3/envs/pygtftk/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.2: cannot open shared object file: No such file or directory

**Comment by dputhier** [comment]
Hi Yasmina,
It seems that this error is related to pysam (which is not a direct dependency of pygtftk but is probably required by pybedtools). 
Did you installed pygtftk using bioconda ?
Otherwise you could also try a 'pip install pysam'.


Maybe you could try a 'pip install

**Comment by yaskermezli** [comment]
Yes!
Solved 
Thank you.

**Comment by xinwei-sher** [comment]
Worked on me! Thanks.
