### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'append'

### ISSUE THREAD

**Issue by gyanmishra** [dputhier/pygtftk#184]
Hi 

I am having the below mentioned issue while running gtftk ologram --more-bed option. 

```
Traceback (most recent call last):
  File "/home2/s225347/.conda/envs/pygtftk/bin/gtftk", line 110, in <module>
    args = main()
  File "/home2/s225347/.conda/envs/pygtftk/bin/gtftk", line 94, in main
    CmdManager.run(args)
  File "/home2/s225347/.conda/envs/pygtftk/lib/python3.9/site-packages/pygtftk/cmd_manager.py", line 963, in run
    fun(**args)
  File "/home2/s225347/.conda/envs/pygtftk/lib/python3.9/site-packages/pygtftk/plugins/ologram.py", line 1091, in ologram
    plot_results(d, data_file, pdf_file, pdf_width, pdf_height, feature_order, more_bed_multiple_overlap,
  File "/home2/s225347/.conda/envs/pygtftk/lib/python3.9/site-packages/pygtftk/plugins/ologram.py", line 1390, in plot_results
    p1, p1_feature_order = plot_this(statname='summed_bp_overlaps',
  File "/home2/s225347/.conda/envs/pygtftk/lib/python3.9/site-packages/pygtftk/plugins/ologram.py", line 1171, in plot_this
    errorbar_mins = errorbar_mins.append(na_series)
  File "/home2/s225347/.conda/envs/pygtftk/lib/python3.9/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'append'
```

**Comment by dputhier** [comment]
This could be related to pandas version. What is your current pandas version ? Could you try with 1.1.2 ?
Best
