### ISSUE TITLE
Error with saveas 

### ISSUE THREAD

**Issue by Norisad** [dputhier/pygtftk#96]
```
|-- 13:37:38-DEBUG-ologram : Exclusion completed for the BED PEAKS file in 5.469421148300171 s
 |-- 13:37:38-INFO-ologram : Processing user-defined regions (bed format).
 |-- 13:37:38-INFO-ologram : Processing ZNF263
Traceback (most recent call last):
  File "/gpfs/tagc/home/sadouni/Apps/anaconda3/envs/snakemake/bin/gtftk", line 4, in <module>
    __import__('pkg_resources').run_script('pygtftk==1.0.5.dev0+067f', 'gtftk')
  File "/gpfs/tagc/home/sadouni/Apps/anaconda3/envs/snakemake/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs/tagc/home/sadouni/Apps/anaconda3/envs/snakemake/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/tagc/home/sadouni/Apps/anaconda3/envs/snakemake/lib/python3.6/site-packages/pygtftk-1.0.5.dev0+067f-py3.6-linux-x86_64.egg/EGG-INFO/scripts/gtftk", line 104, in <module>
    args = main()
  File "/gpfs/tagc/home/sadouni/Apps/anaconda3/envs/snakemake/lib/python3.6/site-packages/pygtftk-1.0.5.dev0+067f-py3.6-linux-x86_64.egg/EGG-INFO/scripts/gtftk", line 89, in main
    CmdManager.run(args)
  File "/gpfs/tagc/home/sadouni/Apps/anaconda3/envs/snakemake/lib/python3.6/site-packages/pygtftk-1.0.5.dev0+067f-py3.6-linux-x86_64.egg/pygtftk/cmd_manager.py", line 957, in run
    fun(**args)
  File "/gpfs/tagc/home/sadouni/Apps/anaconda3/envs/snakemake/lib/python3.6/site-packages/pygtftk-1.0.5.dev0+067f-py3.6-linux-x86_64.egg/pygtftk/plugins/ologram.py", line 774, in ologram
    bed_anno.saveas(tmp_bed.name)
AttributeError: '_io.TextIOWrapper' object has no attribute 'saveas'
[Wed Apr 17 13:38:15 2019]
Error in rule ologram:
    jobid: 0
    output: output/pgk_r1.-1/ZNF263/00_ologram_stats.tsv

RuleException:
CalledProcessError in line 61 of /gpfs/tagc/home/sadouni/peak_anno_test/snake_file.py:
Command 'set -euo pipefail;  set +u; source /gpfs/tagc/home/sadouni/Apps/anaconda3/bin/activate snakemake; set -u
    gtftk ologram -z -V 3 -k 12 -p input/silencer/pgk_r1.-1.mm10.bed -c mm10_chr_size.txt --more-bed /gpfs/tagc/home/sadouni/tf/split_tf_filtered/ZNF263.bed --no-date  -o output/pgk_r1.-1/ZNF263 --more-bed-labels ZNF263 -e input/exclude_region/exclude_dhs.mm10.bed' returned non-zero exit status 1.
```

**Comment by qferre** [comment]
Should be fixed in 25f19302444b8d94d6fcc14a7314789feb5d98da. Reopen if needed.
